# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    hostname: banco_dados
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: found&lost
    ports:
      - 5432:5432
    networks:
      - backend

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - 5253:5253
    depends_on:
      - db
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
