version: '3.4'

services:
  db:
    hostname: banco_dados
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: found&lost
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - $HOME/.postgres-data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
  frontend:
