version: '3.4'

services:
  found-and-lost:
    container_name: container-webapi
    image: ${DOCKER_REGISTRY-}foundandlost
    build:
      context: .
      dockerfile: found-and-lost/Dockerfile
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    hostname: banco_dados
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: found&lost
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
